let firebaseConfig;

if (process.env.NODE_ENV === 'production') {
  // When deployed to either the development, staging, or production Firebase Hosting environments,
  // the Firebase config will be stored in firebaseConfig.json. This file is generated by the
  // npm build scripts in package.json and is not checked into the repo.
  firebaseConfig = require(`./firebaseConfig.json`);
} else {
  // When doing local development, pull the Firebase config from the config/ directory. Use a
  // variable for the config filename so React will not fail to compile things because the config
  // file is actually outside the src/ directory.
  try {
    const configFilename = 'config.dev.json';
    firebaseConfig = require(`../../config/${configFilename}`).firebase;
  } catch (error) {
    // eslint-disable-next-line no-console
    console.log('Failed to load config file:', error);
  }
}

export default firebaseConfig;
